//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hermes.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGE_CLASSES
    {
        public int CATEGORY_ID { get; set; }
        public string CATEGORY_TEXT { get; set; }
        public Nullable<decimal> AGE_START { get; set; }
        public Nullable<decimal> AGE_END { get; set; }
    }
}
