//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hermes.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AITISIS
    {
        public int AITISI_ID { get; set; }
        public Nullable<int> PROSKLISI_ID { get; set; }
        public Nullable<System.DateTime> AITISI_DATE { get; set; }
        public string AITISI_PROTOCOL { get; set; }
        public Nullable<int> STATION_ID { get; set; }
        public Nullable<int> PARENTS_ID { get; set; }
        public Nullable<int> CHILD_ID { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
        public Nullable<decimal> AGE { get; set; }
        public Nullable<int> AGE_CATEGORY { get; set; }
        public Nullable<int> MORIA_SOCIAL { get; set; }
        public Nullable<int> MORIA_OAED { get; set; }
        public Nullable<int> MORIA_INCOME { get; set; }
        public Nullable<int> MORIA_FAMILY { get; set; }
        public Nullable<int> MORIA_REREGISTER { get; set; }
        public Nullable<int> MORIA_SIBLING { get; set; }
        public Nullable<int> MORIA_TOTAL { get; set; }
        public Nullable<int> RANKING { get; set; }
        public Nullable<bool> ENSTASI { get; set; }
        public string APOKLEISMOS_AITIA { get; set; }
        public string EPITROPI1_TEXT { get; set; }
        public string EPITROPI2_TEXT { get; set; }
        public Nullable<bool> RE_REGISTRATION { get; set; }
    
        public virtual PARENTS PARENTS { get; set; }
        public virtual CHILDREN CHILDREN { get; set; }
    }
}
