//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hermes.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gridSTATEMENT_DATA
    {
        public int STATEMENT_ID { get; set; }
        public Nullable<System.DateTime> STATEMENT_DATE { get; set; }
        public Nullable<int> PROSKLISI_ID { get; set; }
        public string PROTOCOL { get; set; }
        public string SY_TEXT { get; set; }
        public Nullable<int> PARENTS_ID { get; set; }
        public Nullable<int> STATION_ID { get; set; }
        public string STATION_NAME { get; set; }
        public string FATHER_FULLNAME { get; set; }
        public string MOTHER_FULLNAME { get; set; }
        public Nullable<int> FATHER_JOBSECTOR { get; set; }
        public Nullable<int> MOTHER_JOBSECTOR { get; set; }
    }
}
