//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hermes.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gridPARENT_DATA
    {
        public int PARENTS_ID { get; set; }
        public string FATHER_FULLNAME { get; set; }
        public string MOTHER_FULLNAME { get; set; }
        public string FATHER_PHONEHOME { get; set; }
        public string FATHER_PHONEWORK { get; set; }
        public string FATHER_PHONEMOBILE { get; set; }
        public string MOTHER_PHONEHOME { get; set; }
        public string MOTHER_PHONEWORK { get; set; }
        public string MOTHER_PHONEMOBILE { get; set; }
        public Nullable<int> STATION_ID { get; set; }
        public Nullable<int> AITISI_ID { get; set; }
        public Nullable<int> PROSKLISI_ID { get; set; }
    }
}
