//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hermes.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gridAITISEIS_DATA
    {
        public int AITISI_ID { get; set; }
        public string AITISI_PROTOCOL { get; set; }
        public Nullable<System.DateTime> AITISI_DATE { get; set; }
        public string PROTOCOL { get; set; }
        public Nullable<int> STATION_ID { get; set; }
        public Nullable<int> SCHOOL_YEAR { get; set; }
        public string SY_TEXT { get; set; }
        public string FULLNAME { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public Nullable<decimal> AGE { get; set; }
        public Nullable<int> GENDER { get; set; }
        public Nullable<int> PARENTS_ID { get; set; }
        public Nullable<int> AGE_CATEGORY { get; set; }
    }
}
