//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hermes.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HermesDBEntities : DbContext
    {
        public HermesDBEntities()
            : base("name=HermesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APP_STATUS> APP_STATUS { get; set; }
        public virtual DbSet<SYS_GENDERS> SYS_GENDERS { get; set; }
        public virtual DbSet<SYS_DIMOS> SYS_DIMOS { get; set; }
        public virtual DbSet<SYS_PERIFERIES> SYS_PERIFERIES { get; set; }
        public virtual DbSet<SYS_STATIONS> SYS_STATIONS { get; set; }
        public virtual DbSet<USER_ADMINS> USER_ADMINS { get; set; }
        public virtual DbSet<USER_STATIONS> USER_STATIONS { get; set; }
        public virtual DbSet<sqlUSER_STATION> sqlUSER_STATION { get; set; }
        public virtual DbSet<USER_PARENTS> USER_PARENTS { get; set; }
        public virtual DbSet<PARENT_TYPES> PARENT_TYPES { get; set; }
        public virtual DbSet<SYS_SCHOOLYEARS> SYS_SCHOOLYEARS { get; set; }
        public virtual DbSet<PROSKLISIS_STATUS> PROSKLISIS_STATUS { get; set; }
        public virtual DbSet<SYS_PERIFERIAKES> SYS_PERIFERIAKES { get; set; }
        public virtual DbSet<FAMILY_STATUS> FAMILY_STATUS { get; set; }
        public virtual DbSet<SYS_NATIONALITIES> SYS_NATIONALITIES { get; set; }
        public virtual DbSet<PARENTS> PARENTS { get; set; }
        public virtual DbSet<sqlCHILD_SELECTOR> sqlCHILD_SELECTOR { get; set; }
        public virtual DbSet<UPLOADS> UPLOADS { get; set; }
        public virtual DbSet<UPLOADS_FILES> UPLOADS_FILES { get; set; }
        public virtual DbSet<JOB_SECTORS> JOB_SECTORS { get; set; }
        public virtual DbSet<sqlPARENT_INFO> sqlPARENT_INFO { get; set; }
        public virtual DbSet<NUMBERS> NUMBERS { get; set; }
        public virtual DbSet<SYS_YESNO> SYS_YESNO { get; set; }
        public virtual DbSet<gridPARENT_DATA> gridPARENT_DATA { get; set; }
        public virtual DbSet<gridAITISEIS_DATA> gridAITISEIS_DATA { get; set; }
        public virtual DbSet<gridSTATEMENT_DATA> gridSTATEMENT_DATA { get; set; }
        public virtual DbSet<sqlAPPLICANT_INFO> sqlAPPLICANT_INFO { get; set; }
        public virtual DbSet<gridUSER_PARENTS> gridUSER_PARENTS { get; set; }
        public virtual DbSet<sqlCHILDREN_DATA> sqlCHILDREN_DATA { get; set; }
        public virtual DbSet<TAXISNET> TAXISNET { get; set; }
        public virtual DbSet<sqlUSER_PARENT_SELECT> sqlUSER_PARENT_SELECT { get; set; }
        public virtual DbSet<FAMILY_INCOME> FAMILY_INCOME { get; set; }
        public virtual DbSet<mor_AITISI_DATA> mor_AITISI_DATA { get; set; }
        public virtual DbSet<mor_AITISI_MORIA> mor_AITISI_MORIA { get; set; }
        public virtual DbSet<RANKINGS> RANKINGS { get; set; }
        public virtual DbSet<sqlAITISEIS_LIST> sqlAITISEIS_LIST { get; set; }
        public virtual DbSet<mor_CHILD_INFO> mor_CHILD_INFO { get; set; }
        public virtual DbSet<AGE_CLASSES> AGE_CLASSES { get; set; }
        public virtual DbSet<CHILDREN> CHILDREN { get; set; }
        public virtual DbSet<PROSKLISIS> PROSKLISIS { get; set; }
        public virtual DbSet<STATEMENTS> STATEMENTS { get; set; }
        public virtual DbSet<AITISIS> AITISIS { get; set; }
        public virtual DbSet<rep_AITISI_INFO_MORIA> rep_AITISI_INFO_MORIA { get; set; }
        public virtual DbSet<sqlCHILDREN_POPULATOR> sqlCHILDREN_POPULATOR { get; set; }
        public virtual DbSet<sqlUPLOADED_FILES> sqlUPLOADED_FILES { get; set; }
        public virtual DbSet<SUPPORT> SUPPORT { get; set; }
        public virtual DbSet<sqlPARENT_SELECTOR> sqlPARENT_SELECTOR { get; set; }
    }
}
