//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hermes.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mor_AITISI_MORIA
    {
        public int AITISI_ID { get; set; }
        public Nullable<int> STATION_ID { get; set; }
        public Nullable<int> PROSKLISI_ID { get; set; }
        public string PROSKLISI_PROTOCOL { get; set; }
        public string AITISI_PROTOCOL { get; set; }
        public string CHILD_AMKA { get; set; }
        public string CHILD_NAME { get; set; }
        public Nullable<int> MORIA_SOCIAL { get; set; }
        public Nullable<int> MORIA_OAED { get; set; }
        public Nullable<int> MORIA_INCOME { get; set; }
        public Nullable<int> MORIA_FAMILY { get; set; }
        public Nullable<int> MORIA_REREGISTER { get; set; }
        public Nullable<int> MORIA_SIBLING { get; set; }
        public Nullable<int> MORIA_TOTAL { get; set; }
        public string RANKING { get; set; }
    }
}
