//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hermes.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARENTS()
        {
            this.CHILDREN = new HashSet<CHILDREN>();
            this.STATEMENTS = new HashSet<STATEMENTS>();
            this.AITISIS = new HashSet<AITISIS>();
        }
    
        public int PARENTS_ID { get; set; }
        public string FATHER_FIRSTNAME { get; set; }
        public string FATHER_LASTNAME { get; set; }
        public string MOTHER_FIRSTNAME { get; set; }
        public string MOTHER_LASTNAME { get; set; }
        public string FATHER_AFM { get; set; }
        public string MOTHER_AFM { get; set; }
        public string FATHER_AMKA { get; set; }
        public string MOTHER_AMKA { get; set; }
        public string FATHER_ADT { get; set; }
        public string MOTHER_ADT { get; set; }
        public string FATHER_PASSPORT { get; set; }
        public string MOTHER_PASSPORT { get; set; }
        public string FATHER_ADDRESS { get; set; }
        public string MOTHER_ADDRESS { get; set; }
        public string FATHER_PHONEHOME { get; set; }
        public string FATHER_PHONEWORK { get; set; }
        public string FATHER_PHONEMOBILE { get; set; }
        public string MOTHER_PHONEHOME { get; set; }
        public string MOTHER_PHONEWORK { get; set; }
        public string MOTHER_PHONEMOBILE { get; set; }
        public string FATHER_EMAIL { get; set; }
        public string MOTHER_EMAIL { get; set; }
        public string FATHER_PERMIT { get; set; }
        public string MOTHER_PERMIT { get; set; }
        public Nullable<int> FAMILY_STATUS { get; set; }
        public Nullable<int> CHILD_EPIMELEIA { get; set; }
        public Nullable<int> PARENT_USERID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHILDREN> CHILDREN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STATEMENTS> STATEMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITISIS> AITISIS { get; set; }
    }
}
