//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hermes.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROSKLISIS
    {
        public int PROSKLISI_ID { get; set; }
        public string PROTOCOL { get; set; }
        public Nullable<int> SCHOOL_YEAR { get; set; }
        public Nullable<System.DateTime> DATE_START { get; set; }
        public Nullable<System.DateTime> DATE_END { get; set; }
        public string DIOIKITIS { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<bool> USERVIEW { get; set; }
        public string HOUR_START { get; set; }
        public string HOUR_END { get; set; }
    }
}
