//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hermes.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class rep_AITISI_INFO_MORIA
    {
        public int AITISI_ID { get; set; }
        public Nullable<int> PROSKLISI_ID { get; set; }
        public Nullable<int> STATION_ID { get; set; }
        public string AITISI_PROTOCOL { get; set; }
        public string AMKA { get; set; }
        public string FULLNAME { get; set; }
        public int AGE_CLASS_ID { get; set; }
        public string AGE_CLASS { get; set; }
        public Nullable<bool> FATHER_DISABILITY { get; set; }
        public Nullable<bool> MOTHER_DISABILITY { get; set; }
        public Nullable<bool> CHILD_AMEA { get; set; }
        public Nullable<bool> CHILD_ORPHAN { get; set; }
        public Nullable<bool> PARENT_DIVORCED { get; set; }
        public Nullable<bool> PARENT_INARMY { get; set; }
        public Nullable<bool> DIKAIOYXOI_BOTH { get; set; }
        public string INCOME_TEXT { get; set; }
        public Nullable<int> CHILDREN_NUMBER { get; set; }
        public Nullable<bool> RE_REGISTRATION { get; set; }
        public Nullable<bool> SIBLING_IN_BNS { get; set; }
        public Nullable<int> PARENTS_ID { get; set; }
        public Nullable<int> MORIA_SOCIAL { get; set; }
        public Nullable<int> MORIA_OAED { get; set; }
        public Nullable<int> MORIA_INCOME { get; set; }
        public Nullable<int> MORIA_FAMILY { get; set; }
        public Nullable<int> MORIA_REREGISTER { get; set; }
        public Nullable<int> MORIA_SIBLING { get; set; }
        public Nullable<int> MORIA_TOTAL { get; set; }
        public int WORKING_MOTHER { get; set; }
        public Nullable<decimal> INCOME_AMOUNT { get; set; }
        public Nullable<int> RANKING { get; set; }
        public string RANKING_TEXT { get; set; }
        public string APOKLEISMOS_AITIA { get; set; }
    }
}
