//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hermes.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlAPPLICANT_INFO
    {
        public int USER_ID { get; set; }
        public string USERNAME { get; set; }
        public string PARENT_FULLNAME { get; set; }
        public string PARENT_AFM { get; set; }
        public string PARENT_AMKA { get; set; }
        public string PARENT_PHONEHOME { get; set; }
        public string PARENT_PHONEWORK { get; set; }
        public string PARENT_PHONEMOBILE { get; set; }
        public int PARENTS_ID { get; set; }
    }
}
