//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hermes.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlCHILDREN_DATA
    {
        public int CHILD_ID { get; set; }
        public string AMKA { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public Nullable<int> GENDER { get; set; }
        public Nullable<int> NATIONALITY { get; set; }
        public Nullable<int> PARENTS_ID { get; set; }
        public string PARENT_FULLNAME { get; set; }
        public Nullable<int> STATION_ID { get; set; }
        public Nullable<int> AITISI_ID { get; set; }
        public Nullable<int> PROSKLISI_ID { get; set; }
    }
}
