//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hermes.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlPARENT_INFO
    {
        public int PARENTS_ID { get; set; }
        public string FATHER_FULLNAME { get; set; }
        public string MOTHER_FULLNAME { get; set; }
        public string FATHER_AFM { get; set; }
        public string MOTHER_AFM { get; set; }
        public string FATHER_AMKA { get; set; }
        public string MOTHER_AMKA { get; set; }
        public string FATHER_PHONEHOME { get; set; }
        public string FATHER_PHONEMOBILE { get; set; }
        public string FATHER_PHONEWORK { get; set; }
        public string MOTHER_PHONEHOME { get; set; }
        public string MOTHER_PHONEMOBILE { get; set; }
        public string MOTHER_PHONEWORK { get; set; }
        public string FSTATUS_TEXT { get; set; }
        public string PARENT_TYPETEXT { get; set; }
        public string FATHER_ADDRESS { get; set; }
        public string MOTHER_ADDRESS { get; set; }
        public string FATHER_EMAIL { get; set; }
        public string MOTHER_EMAIL { get; set; }
    }
}
