//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hermes.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_STATIONS
    {
        public int ΣΤΑΘΜΟΣ_ΚΩΔ { get; set; }
        public string ΕΠΩΝΥΜΙΑ { get; set; }
        public string ΤΑΧ_ΔΙΕΥΘΥΝΣΗ { get; set; }
        public string ΓΡΑΜΜΑΤΕΙΑ { get; set; }
        public string ΤΗΛΕΦΩΝΑ { get; set; }
        public string ΦΑΞ { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> ΠΕΡΙΦΕΡΕΙΑΚΗ { get; set; }
        public Nullable<int> ΠΕΡΙΦΕΡΕΙΑ { get; set; }
        public string ΥΠΕΥΘΥΝΟΣ { get; set; }
        public Nullable<int> ΥΠΕΥΘΥΝΟΣ_ΦΥΛΟ { get; set; }
        public string ΚΙΝΗΤΟ { get; set; }
        public Nullable<bool> ΣΥΜΜΕΤΟΧΗ { get; set; }
    
        public virtual SYS_PERIFERIAKES SYS_PERIFERIAKES { get; set; }
    }
}
