//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hermes.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_PERIFERIAKES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_PERIFERIAKES()
        {
            this.SYS_STATIONS = new HashSet<SYS_STATIONS>();
        }
    
        public int ΚΩΔΙΚΟΣ_ΠΕΡΙΦΕΡΕΙΑ { get; set; }
        public string ΕΠΩΝΥΜΙΑ_ΠΕΡΙΦΕΡΕΙΑ { get; set; }
        public string ΠΕΡΙΦ_ΣΥΝΤΟΜΟΓΡΑΦΙΑ { get; set; }
        public string ΤΑΧ_ΔΙΕΥΘΥΝΣΗ { get; set; }
        public string ΕΔΡΑ { get; set; }
        public string ΤΜΗΜΑ { get; set; }
        public string EMAIL { get; set; }
        public string ΤΗΛΕΦΩΝΑ { get; set; }
        public string FAX { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_STATIONS> SYS_STATIONS { get; set; }
    }
}
